### ISSUE TITLE
How to handle MAPE with actuals of 0?

### ISSUE THREAD

**Issue by soumyaray** [ISS-Analytics/pls-predict#4]
How should we handle MAPE computation if 0s are encountered in the actual data?

**Comment by soumyaray** [comment]
what was your solution here, btw?

**Comment by NicholasDanks** [comment]
Use mean of Actual Value instead of Actual Value
Ie.  1/n [ sum [ (mean(Actual) - Forecast) / mean(Actuals) ]]

**Comment by NicholasDanks** [comment]
Use MAPE with na.rm = TRUE and report 
retrun residual histos
