### ISSUE TITLE
validatePredict(): Get overall RMSE/MAD/MAPE

### ISSUE THREAD

**Issue by soumyaray** [ISS-Analytics/pls-predict#5]
Return overall prediction metric across k-folds
- [x] RMSE
- [x] MAPE
- [x] MAD

**Comment by soumyaray** [comment]
For RMSE: http://stats.stackexchange.com/questions/85507/what-is-the-rmse-of-k-fold-cross-validation

**Comment by NicholasDanks** [comment]
Check calculations!!
