### ISSUE TITLE
Change pls-predict arguments

### ISSUE THREAD

**Issue by soumyaray** [ISS-Analytics/pls-predict#6]
- [x] new arguments: `mmMatrix`, `smMatrx`, `data`
- [x] calls `simplePLS()` to create `plsmodel`
- [x] return factor scores

**Comment by NicholasDanks** [comment]
Modified plspredict to return fscore predictions
When running plspredict on full dataset, it returns the same fscores as simplePLS.  Does this mean that plsPredict is not predicting new fscores? 
plsPredict produces and Fscore for every observation of the items. Should this be reduced to a single number? How? Mean?
